import { BRAND } from "@/lib/brand";
import { siteConfig } from "@/config/site";
import { SITE_URL_PLACEHOLDER } from "@/lib/site-url";
import { navigation } from "@/lib/navigation";
import type { SiteSettingsBundle } from "./types";

const HERO_IMAGE_DEFAULT =
  "https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=1000&h=1250&fit=crop&q=85";

export const DEFAULT_SITE_SETTINGS: SiteSettingsBundle = {
  hero: {
    tagline: siteConfig.tagline,
    headline: siteConfig.name,
    subtitle: "Liebevolle Kinderbetreuung für eure besonderen Momente.",
    ctaPrimary: "Jetzt anfragen",
    ctaSecondary: "Unsere Leistungen",
    imageUrl: HERO_IMAGE_DEFAULT,
    badgeQuote: "Jedes Kind verdient einen Tag voller Abenteuer.",
  },
  contact: {
    phone: siteConfig.contact.phone,
    mobile: "",
    email: siteConfig.contact.email,
    contactEmail: siteConfig.contact.email,
    whatsapp: siteConfig.contact.whatsapp,
    whatsappLabel: "WhatsApp",
    instagram: siteConfig.contact.instagram,
    instagramHandle: siteConfig.contact.instagramHandle,
    facebook: "",
    tiktok: "",
    location: siteConfig.contact.location,
    mapsUrl: "https://maps.google.com/?q=NRW+Deutschland",
    responseTime: "Antwort innerhalb von 24 Stunden",
    openingHours: "Mo–Fr 9–18 Uhr · Termine nach Vereinbarung",
  },
  about: {
    founderName: "Lisa",
    imageUrl:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=1000&fit=crop&q=85",
    introText: "Hallo, ich bin Lisa — die Gründerin der Panda-Bande.",
    paragraph1:
      "Panda-Bande entstand aus einer einfachen Überzeugung: Kinder gehören auf Feiern nicht an den Rand, sondern ins Herz des Moments.",
    paragraph2:
      "Was als Herzensprojekt begann, ist heute ein erfahrenes Team aus Betreuern, die mit Kreativität, Geduld und echter Freude arbeiten — damit ihr entspannt feiern könnt.",
    missionText: "Magische Momente für Kinder — sorgenfreie Erlebnisse für Familien.",
    valuesText: "Herzlichkeit, Sicherheit, Kreativität und Verlässlichkeit.",
  },
  footer: {
    tagline: "Mit Herz für kleine Abenteuer.",
    copyrightName: siteConfig.name,
  },
  navigation: {
    items: navigation.map((item) => ({ label: item.label, href: item.href })),
    ctaLabel: "Jetzt anfragen",
    ctaLabelShort: "Anfragen",
  },
  branding: {
    logoUrl: BRAND.master,
    logoDarkUrl: BRAND.master,
    logoLightUrl: BRAND.master,
    logoAlt: BRAND.alt,
    logoTextPrimary: BRAND.textPrimary,
    logoTextSecondary: BRAND.textSecondary,
    brandName: BRAND.shortName,
    tagline: "Kinderevents",
    slogan: siteConfig.tagline,
    primaryColor: BRAND.themeColor,
    accentColor: BRAND.accentColor,
    faviconUrl: BRAND.assets.faviconPng,
    appleTouchIconUrl: BRAND.assets.appleTouchIcon,
    pwaIcon192Url: BRAND.assets.icon192,
    pwaIcon512Url: BRAND.assets.icon512,
    pdfLogoUrl: BRAND.master,
    emailLogoUrl: BRAND.master,
    loginLogoUrl: BRAND.master,
    ogImageUrl: BRAND.assets.ogImage,
    showTextMark: true,
  },
  trustBadges: {
    items: [
      { iconKey: "Award", text: "Antwort innerhalb 24h" },
      { iconKey: "MapPin", text: "NRW & Umgebung" },
      { iconKey: "Calendar", text: "Flexible Buchung" },
      { iconKey: "Sparkles", text: "Individuelle Betreuung" },
    ],
  },
  usps: {
    title: "Warum Panda-Bande?",
    subtitle: "Vertrauen, Herzlichkeit und professionelle Kinderbetreuung — für euer besonderes Event.",
    items: [
      { iconKey: "Users", title: "Erfahrenes Team", description: "Geschulte Betreuerinnen mit Herz und Erfahrung bei Events jeder Größe." },
      { iconKey: "Heart", title: "Liebevoll", description: "Jedes Kind wird individuell wahrgenommen — mit Geduld, Wärme und Einfühlungsvermögen." },
      { iconKey: "Shield", title: "Zuverlässig", description: "Pünktlich, vorbereitet und verlässlich — damit ihr entspannt feiern könnt." },
      { iconKey: "Calendar", title: "Flexible Buchung", description: "Kurzfristige Anfragen, individuelle Zeiten und passende Teamgrößen." },
      { iconKey: "MapPin", title: "NRW & Umgebung", description: "Einsatz in NRW und bundesweit — wir kommen zu eurer Location." },
      { iconKey: "Sparkles", title: "Individuelle Betreuung", description: "Programme nach Alter, Wünschen und Rahmen eures Events." },
    ],
  },
  process: {
    title: "So läuft es ab",
    subtitle: "Von der ersten Anfrage bis zu glücklichen Kindern — in fünf Schritten.",
    speechBubble: "Wir kümmern uns um den Rest!",
    steps: [
      { number: 1, title: "Anfrage", description: "Ihr sendet uns eure Wünsche — kostenlos und unverbindlich.", iconKey: "PartyPopper" },
      { number: 2, title: "Beratung", description: "Wir besprechen Programm, Teamgröße und Ablauf persönlich.", iconKey: "MessageCircle" },
      { number: 3, title: "Planung", description: "Gemeinsam planen wir Material, Zeiten und Betreuung.", iconKey: "Calendar" },
      { number: 4, title: "Event", description: "Unsere Panda-Bande sorgt vor Ort für strahlende Kinderaugen.", iconKey: "Users" },
      { number: 5, title: "Glückliche Kinder", description: "Zufriedene Kinder, entspannte Eltern — Mission erfüllt!", iconKey: "Heart" },
    ],
  },
  sections: {
    usps: {
      title: "Warum Panda-Bande?",
      subtitle: "Professionelle Betreuung mit echter Herzlichkeit — für unvergessliche Momente.",
    },
    services: {
      title: "Unsere Leistungen",
      subtitle: "Von der Hochzeit bis zum Kindergeburtstag — wir gestalten unvergessliche Momente.",
    },
    process: {
      title: "So einfach buchst du uns",
      subtitle: "In fünf Schritten zu eurem unvergesslichen Event.",
    },
    gallery: {
      title: "Einblicke in unsere Arbeit",
      subtitle: "Echte Momente, echte Freude — so sieht Panda-Bande aus.",
    },
    testimonials: {
      title: "Das sagen Eltern",
      subtitle: "Echte Rückmeldungen — freigegeben nach Prüfung durch unser Team.",
    },
    about: {
      title: "Über die Panda-Bande",
      subtitle: "Geschichte, Mission, Werte und Team — alles an einem Ort.",
    },
    news: {
      title: "Aktuelles",
      subtitle: "Neuigkeiten, Tipps und Einblicke von der Panda-Bande.",
    },
    faq: {
      title: "Häufige Fragen",
      subtitle: "Antworten auf die wichtigsten Fragen rund um euer Event.",
    },
    team: {
      title: "Unser Team",
      subtitle: "Die Menschen hinter der Panda-Bande — mit Herz für kleine Abenteurer.",
    },
    contact: {
      title: "Jetzt unverbindlich anfragen",
      subtitle: "Erzählt uns von eurem Event — wir melden uns schnellstmöglich bei euch.",
    },
  },
  publicTeam: {
    title: "Unser Team",
    subtitle: "Liebevolle Betreuerinnen mit Erfahrung, Kreativität und Herz.",
    items: [
      {
        name: "Lisa",
        role: "Gründerin & Leitung",
        description: "Mit viel Herz und Erfahrung koordiniert Lisa jedes Event persönlich.",
        imageUrl:
          "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=1000&fit=crop&q=85",
      },
      {
        name: "Panda-Bande Team",
        role: "Betreuerinnen",
        description: "Unser erfahrenes Team begleitet Kinder liebevoll bei jedem Anlass.",
        imageUrl: "",
      },
    ],
  },
  business: {
    companyName: siteConfig.name,
    shortName: "Panda-Bande",
    slogan: siteConfig.tagline,
    logoUrl: BRAND.master,
    faviconUrl: BRAND.assets.faviconPng,
    street: "",
    zip: "",
    city: "",
    state: "NRW",
    country: "Deutschland",
    address: siteConfig.contact.location,
    managingDirector: "",
    description: siteConfig.description,
    website: SITE_URL_PLACEHOLDER,
    phone: siteConfig.contact.phone,
    email: siteConfig.contact.email,
    iban: "",
    bic: "",
    bankName: "",
    taxNumber: "",
    vatId: "",
    defaultPaymentDays: 14,
    defaultQuoteText: "Vielen Dank für Ihre Anfrage. Wir freuen uns auf Ihre Rückmeldung.",
    defaultInvoiceText: "Vielen Dank für Ihren Auftrag.",
    defaultPaymentText:
      "Bitte überweisen Sie den Rechnungsbetrag innerhalb des Zahlungsziels auf das unten genannte Konto.",
    senderName: siteConfig.name,
    senderEmail: siteConfig.contact.email,
  },
  bank: {
    bankName: "",
    accountHolder: siteConfig.name,
    iban: "",
    bic: "",
    taxNumber: "",
    vatId: "",
    smallBusinessRule: false,
    smallBusinessNotice: "Gemäß § 19 UStG wird keine Umsatzsteuer berechnet.",
    paymentTerms: "Zahlbar innerhalb von 14 Tagen ohne Abzug.",
    dunningNotice: "",
  },
  invoice: {
    quotePrefix: "ANG",
    invoicePrefix: "RE",
    quoteStartNumber: 1,
    invoiceStartNumber: 1,
    yearInNumber: true,
    defaultQuoteDateToday: true,
    defaultInvoiceDateToday: true,
    defaultDueDays: 14,
    defaultPaymentDays: 14,
    showServiceDate: false,
    showEventDate: true,
    defaultTaxRate: 19,
    smallBusinessRule: false,
    taxNoticeText: "",
    discountFieldEnabled: true,
    quoteIntroText: "Vielen Dank für Ihre Anfrage. Wir freuen uns auf Ihre Rückmeldung.",
    quoteClosingText: "Bei Fragen stehen wir Ihnen gerne zur Verfügung.",
    invoiceIntroText: "Vielen Dank für Ihren Auftrag.",
    invoiceClosingText: "Wir freuen uns auf die weitere Zusammenarbeit.",
    paymentInfoText:
      "Bitte überweisen Sie den Rechnungsbetrag innerhalb des Zahlungsziels auf das unten genannte Konto.",
    paymentReferenceText: "Verwendungszweck: Rechnungsnummer angeben.",
    pdfFooterText: "",
    legalNoticeText: "Bitte juristisch prüfen — Platzhalter für rechtliche Hinweise auf Rechnungen.",
  },
  seo: {
    primaryDomain: "",
    wwwDomain: "",
    canonicalBaseUrl: "",
    metaTitle: `${siteConfig.name} — Liebevolle Kinderbetreuung für euer Event`,
    metaDescription: siteConfig.description,
    ogImageUrl: BRAND.assets.ogImage,
    socialPreviewText: siteConfig.tagline,
    googleSiteVerification: "",
    googleAnalyticsId: "",
    microsoftClarityId: "",
    robotsIndex: true,
    sitemapEnabled: true,
  },
  legal: {
    impressumResponsible: "",
    impressumDisclaimer:
      "Dies ist eine Platzhalterseite. Bitte ersetzen Sie diesen Inhalt durch ein rechtsgültiges Impressum, bevor die Website öffentlich genutzt wird. Bitte juristisch prüfen.",
    privacyContactEmail: siteConfig.contact.email,
    privacyCustomText: "",
    agbTitle: "Allgemeine Geschäftsbedingungen",
    agbContent:
      "Platzhalter — AGB-Text bitte juristisch prüfen und hier einfügen.",
    cookieNoticeText:
      "Wir verwenden nur technisch notwendige Speicherung für die Website-Funktion. Details in der Datenschutzerklärung.",
    inquiryPrivacyHint:
      "Mit dem Absenden stimmen Sie der Verarbeitung Ihrer Daten gemäß unserer Datenschutzerklärung zu.",
    reviewPrivacyHint:
      "Mit dem Absenden Ihrer Bewertung stimmen Sie der Veröffentlichung nach Freigabe zu.",
    bookingPrivacyHint: "Ihre Daten werden nur zur Bearbeitung Ihrer Anfrage verwendet.",
    invoiceLegalNotice: "Bitte juristisch prüfen.",
    placeholderNotice: "Bitte juristisch prüfen — Platzhaltertext.",
  },
  email: {
    companyName: siteConfig.name,
    senderName: siteConfig.name,
    senderEmail: siteConfig.contact.email,
    replyTo: siteConfig.contact.email,
    copyToEmail: siteConfig.contact.email,
    quoteCopyTo: siteConfig.contact.email,
    invoiceCopyTo: siteConfig.contact.email,
    inquiryRecipient: siteConfig.contact.email,
    inquiryCopyTo: "",
    adminNotificationEmail: siteConfig.contact.email,
    inquiryAutoReplyEnabled: false,
    inquiryAutoReplySubject: "Ihre Anfrage bei Panda-Bande — wir melden uns",
    inquiryAutoReplyText:
      "Vielen Dank für Ihre Anfrage. Wir haben Ihre Nachricht erhalten und melden uns schnellstmöglich.",
    quoteSenderEmail: "",
    quoteReplyTo: "",
    quoteSubjectTemplate: "Angebot {number} — {company}",
    quoteEmailBody: "",
    invoiceSenderEmail: "",
    invoiceReplyTo: "",
    invoiceSubjectTemplate: "Rechnung {number} — {company}",
    invoiceEmailBody: "",
    passwordResetSenderEmail: "",
    securityNotificationSender: "",
    loginAlertRecipient: "",
    applicationEmail: "",
    applicationCopyTo: "",
    customAddresses: {
      info: "info@",
      kontakt: "kontakt@",
      rechnung: "rechnung@",
      angebote: "angebote@",
    },
  },
};
